from __future__ import annotations

import subprocess
from pathlib import Path

# Marker used to recognize (and safely remove) a hook written by becwright.
_HOOK_MARK = "# >>> becwright hook >>>"

# Prefer a project-local install (npm/pnpm devDependency) over a global one, so
# the hook works whether becwright is on PATH or only in node_modules/.bin.
_HOOK_CONTENT = f"""#!/bin/sh
{_HOOK_MARK}
# Generated by `becwright install`. Do not edit by hand: use `becwright uninstall`.
if [ -x "./node_modules/.bin/becwright" ]; then
    exec ./node_modules/.bin/becwright check
elif command -v becwright >/dev/null 2>&1; then
    exec becwright check
else
    echo "becwright not found. Install it globally (pipx / npm i -g) or as a devDependency." >&2
    exit 1
fi
# <<< becwright hook <<<
"""


class NotAGitRepo(RuntimeError):
    pass


def repo_root() -> Path:
    res = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True,
    )
    if res.returncode != 0:
        raise NotAGitRepo("You are not inside a git repository.")
    return Path(res.stdout.strip())


def files_to_check(root: Path, *, all_files: bool) -> list[str]:
    if all_files:
        cmd = ["git", "ls-files"]
    else:
        cmd = ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"]
    res = subprocess.run(cmd, cwd=root, capture_output=True, text=True)
    return [line for line in res.stdout.splitlines() if line.strip()]


def _hook_path(root: Path) -> Path:
    return root / ".git" / "hooks" / "pre-commit"


def install_hook(root: Path) -> tuple[bool, str]:
    hook = _hook_path(root)
    if hook.exists():
        content = hook.read_text(encoding="utf-8")
        if _HOOK_MARK in content:
            return False, "The becwright hook was already installed."
        # Never clobber a pre-commit hook we did not write.
        return False, (
            f"A non-becwright pre-commit already exists at {hook}. "
            "Leaving it; remove or integrate it by hand."
        )
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(_HOOK_CONTENT, encoding="utf-8")
    hook.chmod(0o755)
    return True, f"Hook installed at {hook}."


def uninstall_hook(root: Path) -> tuple[bool, str]:
    hook = _hook_path(root)
    if not hook.exists():
        return False, "No pre-commit hook to remove."
    if _HOOK_MARK not in hook.read_text(encoding="utf-8"):
        return False, "The existing pre-commit is not becwright's; leaving it."
    hook.unlink()
    return True, "becwright hook uninstalled."
