from __future__ import annotations

import contextlib
import shutil
import subprocess
import tempfile
from collections.abc import Iterator
from pathlib import Path

# Marker used to recognize (and safely remove) a hook written by becwright.
_HOOK_MARK = "# >>> becwright hook >>>"

# Prefer a project-local install (npm/pnpm devDependency) over a global one, so
# the hook works whether becwright is on PATH or only in node_modules/.bin.
def _hook_body(command: str) -> str:
    return f"""#!/bin/sh
{_HOOK_MARK}
# Generated by `becwright install`. Do not edit by hand: use `becwright uninstall`.
if [ -x "./node_modules/.bin/becwright" ]; then
    exec ./node_modules/.bin/becwright {command}
elif command -v becwright >/dev/null 2>&1; then
    exec becwright {command}
else
    echo "becwright not found. Install it globally (pipx / npm i -g) or as a devDependency." >&2
    exit 1
fi
# <<< becwright hook <<<
"""


# The pre-commit hook checks the files; the commit-msg hook checks the message
# (git passes its path as $1). Each is installed and removed independently.
_HOOKS = {
    "pre-commit": _hook_body("check"),
    "commit-msg": _hook_body('check-msg "$1"'),
}


class NotAGitRepo(RuntimeError):
    pass


class GitError(RuntimeError):
    pass


def repo_root(cwd: Path | None = None) -> Path:
    res = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=cwd, capture_output=True, text=True,
    )
    if res.returncode != 0:
        raise NotAGitRepo("You are not inside a git repository.")
    return Path(res.stdout.strip())


def files_to_check(
    root: Path, *, all_files: bool = False, diff_base: str | None = None
) -> list[str]:
    if diff_base:
        return _files_changed_since(root, diff_base)
    if all_files:
        cmd = ["git", "ls-files"]
    else:
        cmd = ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"]
    res = subprocess.run(cmd, cwd=root, capture_output=True, text=True)
    return [line for line in res.stdout.splitlines() if line.strip()]


def _files_changed_since(root: Path, base: str) -> list[str]:
    """Files added/copied/modified between `base` and HEAD, using the three-dot
    range (`base...HEAD`) so it reports exactly what the branch introduced since it
    diverged — the same set a pull request shows as "Files changed". Raises `GitError`
    when `base` is unknown so a CI run fails loudly instead of silently passing on an
    empty file list (e.g. a shallow clone without the base ref)."""
    res = subprocess.run(
        ["git", "diff", "--name-only", "--diff-filter=ACM", f"{base}...HEAD"],
        cwd=root, capture_output=True, text=True,
    )
    if res.returncode != 0:
        detail = res.stderr.strip() or f"unknown ref '{base}'"
        raise GitError(
            f"Could not diff against '{base}': {detail}\n"
            "In CI, check out full history (actions/checkout with fetch-depth: 0) "
            "and make sure the base branch is fetched."
        )
    return [line for line in res.stdout.splitlines() if line.strip()]


def _staged_blob(root: Path, path: str) -> bytes | None:
    # `:0:<path>` is the staged (index) version of the file, which is exactly
    # what the commit will record — not the working-tree copy that may differ.
    res = subprocess.run(
        ["git", "show", f":0:{path}"],
        cwd=root, capture_output=True,
    )
    return res.stdout if res.returncode == 0 else None


@contextlib.contextmanager
def staged_worktree(root: Path, files: list[str]) -> Iterator[Path]:
    """Materialize the staged content of `files` into a temp dir, so checks see
    exactly what is being committed instead of the working tree (which may hold
    unstaged edits). The working-tree `.bec/` tooling is copied alongside so that
    custom checks referenced by relative paths still resolve."""
    tmp = Path(tempfile.mkdtemp(prefix="becwright-"))
    try:
        for path in files:
            blob = _staged_blob(root, path)
            if blob is None:
                continue
            dest = tmp / path
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(blob)
        bec = root / ".bec"
        if bec.is_dir():
            shutil.copytree(bec, tmp / ".bec", dirs_exist_ok=True)
        yield tmp
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _hook_path(root: Path, name: str = "pre-commit") -> Path:
    return root / ".git" / "hooks" / name


def _install_named(root: Path, name: str) -> tuple[bool, str]:
    hook = _hook_path(root, name)
    if hook.exists():
        if _HOOK_MARK in hook.read_text(encoding="utf-8"):
            return False, f"The becwright {name} hook was already installed."
        # Never clobber a hook we did not write.
        return False, (
            f"A non-becwright {name} already exists at {hook}. "
            "Leaving it; remove or integrate it by hand."
        )
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(_HOOKS[name], encoding="utf-8")
    hook.chmod(0o755)
    return True, f"{name} hook installed at {hook}."


def _uninstall_named(root: Path, name: str) -> tuple[bool, str]:
    hook = _hook_path(root, name)
    if not hook.exists():
        return False, f"No {name} hook to remove."
    if _HOOK_MARK not in hook.read_text(encoding="utf-8"):
        return False, f"The existing {name} is not becwright's; leaving it."
    hook.unlink()
    return True, f"becwright {name} hook uninstalled."


def hook_state(root: Path, name: str = "pre-commit") -> str:
    """'becwright' (ours), 'foreign' (someone else's), or 'missing'."""
    hook = _hook_path(root, name)
    if not hook.exists():
        return "missing"
    return "becwright" if _HOOK_MARK in hook.read_text(encoding="utf-8") else "foreign"


def hooks_path_override(root: Path) -> str | None:
    """The value of `core.hooksPath` when set (e.g. `.husky/_` by Husky), else None.
    When set, git ignores `.git/hooks` entirely — including a becwright hook there."""
    res = subprocess.run(
        ["git", "config", "core.hooksPath"],
        cwd=root, capture_output=True, text=True,
    )
    value = res.stdout.strip()
    return value or None


def hook_manager(root: Path) -> str | None:
    """The hook manager this repo appears to use: 'husky', 'pre-commit', or None."""
    if (root / ".husky").is_dir():
        return "husky"
    if (root / ".pre-commit-config.yaml").is_file():
        return "pre-commit"
    return None


def install_hook(root: Path) -> tuple[bool, str]:
    return _install_named(root, "pre-commit")


def install_msg_hook(root: Path) -> tuple[bool, str]:
    return _install_named(root, "commit-msg")


def uninstall_hook(root: Path) -> tuple[bool, str]:
    return _uninstall_named(root, "pre-commit")


def uninstall_msg_hook(root: Path) -> tuple[bool, str]:
    return _uninstall_named(root, "commit-msg")
