from __future__ import annotations

import contextlib
import shutil
import subprocess
import tempfile
from collections.abc import Iterator
from pathlib import Path

# Marker used to recognize (and safely remove) a hook written by becwright.
_HOOK_MARK = "# >>> becwright hook >>>"

# Prefer a project-local install (npm/pnpm devDependency) over a global one, so
# the hook works whether becwright is on PATH or only in node_modules/.bin.
_HOOK_CONTENT = f"""#!/bin/sh
{_HOOK_MARK}
# Generated by `becwright install`. Do not edit by hand: use `becwright uninstall`.
if [ -x "./node_modules/.bin/becwright" ]; then
    exec ./node_modules/.bin/becwright check
elif command -v becwright >/dev/null 2>&1; then
    exec becwright check
else
    echo "becwright not found. Install it globally (pipx / npm i -g) or as a devDependency." >&2
    exit 1
fi
# <<< becwright hook <<<
"""


class NotAGitRepo(RuntimeError):
    pass


def repo_root(cwd: Path | None = None) -> Path:
    res = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=cwd, capture_output=True, text=True,
    )
    if res.returncode != 0:
        raise NotAGitRepo("You are not inside a git repository.")
    return Path(res.stdout.strip())


def files_to_check(root: Path, *, all_files: bool) -> list[str]:
    if all_files:
        cmd = ["git", "ls-files"]
    else:
        cmd = ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"]
    res = subprocess.run(cmd, cwd=root, capture_output=True, text=True)
    return [line for line in res.stdout.splitlines() if line.strip()]


def _staged_blob(root: Path, path: str) -> bytes | None:
    # `:0:<path>` is the staged (index) version of the file, which is exactly
    # what the commit will record — not the working-tree copy that may differ.
    res = subprocess.run(
        ["git", "show", f":0:{path}"],
        cwd=root, capture_output=True,
    )
    return res.stdout if res.returncode == 0 else None


@contextlib.contextmanager
def staged_worktree(root: Path, files: list[str]) -> Iterator[Path]:
    """Materialize the staged content of `files` into a temp dir, so checks see
    exactly what is being committed instead of the working tree (which may hold
    unstaged edits). The working-tree `.bec/` tooling is copied alongside so that
    custom checks referenced by relative paths still resolve."""
    tmp = Path(tempfile.mkdtemp(prefix="becwright-"))
    try:
        for path in files:
            blob = _staged_blob(root, path)
            if blob is None:
                continue
            dest = tmp / path
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(blob)
        bec = root / ".bec"
        if bec.is_dir():
            shutil.copytree(bec, tmp / ".bec", dirs_exist_ok=True)
        yield tmp
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _hook_path(root: Path) -> Path:
    return root / ".git" / "hooks" / "pre-commit"


def install_hook(root: Path) -> tuple[bool, str]:
    hook = _hook_path(root)
    if hook.exists():
        content = hook.read_text(encoding="utf-8")
        if _HOOK_MARK in content:
            return False, "The becwright hook was already installed."
        # Never clobber a pre-commit hook we did not write.
        return False, (
            f"A non-becwright pre-commit already exists at {hook}. "
            "Leaving it; remove or integrate it by hand."
        )
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(_HOOK_CONTENT, encoding="utf-8")
    hook.chmod(0o755)
    return True, f"Hook installed at {hook}."


def uninstall_hook(root: Path) -> tuple[bool, str]:
    hook = _hook_path(root)
    if not hook.exists():
        return False, "No pre-commit hook to remove."
    if _HOOK_MARK not in hook.read_text(encoding="utf-8"):
        return False, "The existing pre-commit is not becwright's; leaving it."
    hook.unlink()
    return True, "becwright hook uninstalled."
